Squashed 'meta-intel/' changes from f7ba543caa2..2740652fdb5
2740652fdb5 ipmctl: fix build issue undefined reference to `main`

git-subtree-dir: meta-intel
git-subtree-split: 2740652fdb5f85d593e43a7dfea7af8c513aee93